package com.payline.payment.docapost.utils.type;

/**
 * Created by Thales on 04/09/2018.
 */
public enum WSRequestResultEnum {

    EMPTY_MANDATE_CREDITOR_AUTHORIZED_FLOWS,
    MISSING_OR_INVALID_FIELD,
    UNIQUE_CPVALUE_VIOLATION,
    BPI_INVALIDCOUNTRY,
    ACCOUNT_CREATION_NOT_AUTHORIZED,
    SIGN_DATE_IN_FUTURE,
    CONTEXT_NOT_FOUND,
    DEFAULT_CREDITOR_ACCOUNT_MISSING,
    CREDITOR_NOT_ACTIVE,
    CREDITOR_NOT_FOUND,
    CREDITOR_MISSING,
    RUM_NOT_UNIQUE,
    CANCEL_NOT_ALLOWED,
    UNSUPPORTED_MANDATE_FLOW_CHANGE,
    MISSING_MANDATE_FLOW_NAME,
    CONTEXT_ID_MISSING,
    RUM_NOT_ALLOWED,
    DEBTOR_NAME_WITH_CHARACTER_NOT_SEPA,
    MANDATE_NOT_VALID,
    EXISTING_ORDER,
    NOT_FOUND,
    UNAUTHORIZED

}